version: '3'

services:
  notification-service:
    container_name: notification-service
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_OUTPUT=json
    ports:
      - "8082:8082"
    networks:
      - notification-compose-network
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs
      # AWS
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_OUTPUT=json
    ports:
      - "4566:4566"
    networks:
      - notification-compose-network
networks:
  notification-compose-network:
    driver: bridge

#aws sqs --endpoint-url=http://localhost:4566 create-queue --queue-name notification-queue-sqs --region sa-east-1
#aws sqs --endpoint-url=http://localhost:4566 send-message --queue-url  notification-queue-sqs --message-body "Information about the largest city in Any Region."