
spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer_db
server:
  port: 8080
---

spring:
  profiles: docker-test
  data:
    mongodb:
      host: mongo
      port: 27017
      database: customer_db
server:
  port: 8080