spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transaction_db
cloud:
  aws:
    region:
      static: sa-east-1
sqs:
  region: sa-east-1
  endpoint: http://localhost:4566
  queueName: /000000000000/notification-queue-sqs

authorizer-XPTO:
  url: https://run.mocky.io/v3

customer-service:
  url: http://localhost:8080
account-service:
  url: http://localhost:8081/

server:
  port: 8082

---
spring:
  profiles: docker-test
  data:
    mongodb:
      host: mongo
      port: 27017
      database: transaction_db
cloud:
  aws:
    region:
      static: sa-east-1
sqs:
  region: sa-east-1
  endpoint: http://localstack:4566
  queueName: /000000000000/notification-queue-sqs

authorizer-XPTO:
  url: https://run.mocky.io/v3

customer-service:
  url: http://customer-service:8080
account-service:
  url: http://account-service:8081/

server:
  port: 8082