cloud:
  aws:
    region:
      static: sa-east-1

sqs:
  region: sa-east-1
  endpoint: http://localhost:4566
  queueName: notifcation-queue-sqs

authorizer-XPTO:
  url: https://run.mocky.io/v3

customer-service:
  url: http://localhost:8080
account-service:
  url: http://localhost:8081/

server:
  port: 8082