version: '3'

services:
  money-transfer-service:
    container_name: money-transfer-service
    build: .
    ports:
      - "8082:8082"
    networks:
      - mongo-compose-network
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/diegolucas/mongotmp:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge